### PR TITLE
Combine all configs

### PR DESCRIPTION
**Pull request by aleksul**
All the configs were combined inside `pyproject.toml`, as discussed in #58.
Additionally, `yapf` needs `toml` package to read from `pyproject.toml`, so I added it to `format_requirements.txt`.

### CODE REVIEW

**Comment by AustinScola** [comment]
The formatting check is taking a long time with this change? My first thought would be that the ignores aren't properly configured?

**Comment by aleksul** [comment]
> 
> 
> The formatting check is taking a long time with this change? My first thought would be that the ignores aren't properly configured?

Support for `yapf ignore` in `pyproject.toml` seems to be unreleased yet. I reverted this change.

**Comment by AustinScola** [comment]
> Support for `yapf ignore` in `pyproject.toml` seems to be unreleased yet. I reverted this change.

Was the addition of the `toml` dep for `yapf` style config, ignores, or both?

**Comment by aleksul** [comment]
> 
> 
> > Support for `yapf ignore` in `pyproject.toml` seems to be unreleased yet. I reverted this change.
> 
> Was the addition of the `toml` dep for `yapf` style config, ignores, or both?

I think both. Give me a minute, I will double-check this.

**Comment by aleksul** [comment]
As i thought

```bash
Successfully installed isort-5.8.0 yapf-0.31.0
yapf: toml package is needed for using pyproject.toml as a configuration file
```

**Pull request merged**
