### PR TITLE
Support for Darwin (MacOs) platform

### PR DESCRIPTION
**Pull request by frepond**
@AustinScola started a new fork based on your latest work and made minimal changes to make it work on MacOs.

### CODE REVIEW

**Comment by AustinScola** [comment]
@frepond are these the only changes needed for MacOS support? Have you verified that it works on a MacOS machine?

**Comment by frepond** [comment]
@AustinScola yes, those are the only changes needed. I've my fork working in a microservice on MacOs. In order to contribute to this on MacOs you need to install `greadlink` and make an alias `alias readlink=greadlink`.

Once again thanks for your great work!

**Comment by AustinScola** [comment]
> @AustinScola yes, those are the only changes needed. I've my fork working in a microservice on MacOs.

Awesome!

In order to contribute to this on MacOs you need to install `greadlink` and make an alias `alias readlink=greadlink`.

What is `greadlink`?

> Once again thanks for your great work!

Happy to have helped and thanks for the contribution!

**Comment by frepond** [comment]
> What is `greadlink`?

GNU version of readlink for MacOs.

**Comment by AustinScola** [comment]
Ahhh, for the `HERE` lines in the scripts. Your previous PR had a line to update those? If you think that is a good change do you want to add it in another PR (and make an Issue for it too)?

**Comment by frepond** [comment]
@AustinScola the `HERE` is only needed for development and the problem can be solved with `greadlink`.  If you think it's better to have a compatible version on both platform than doing the alias I could do the PR. Just let me know.

**Comment by AustinScola** [comment]
Maybe we can just add a note to `CONTRIBUTING.md`?

**Pull request merged**
